-- Database
-- #IMPORT: 00 - DB\\CategoryDB.lua
-- #IMPORT: 00 - DB\\ClassInfoDB.lua
-- #IMPORT: 00 - DB\\ItemDB.lua
-- #IMPORT: 00 - DB\\MountDB.lua
-- #IMPORT: 00 - DB\\ObjectDB.lua
-- #IMPORT: 00 - DB\\PetDB.lua
-- #IMPORT: 00 - DB\\ToyDB.lua

-- Dungeons & Raids
-- Classic
-- #IMPORT: 01 - Dungeons Raids\\1 - Classic\\0.5 Tier 0.5 Sets.lua
-- #IMPORT: 01 - Dungeons Raids\\1 - Classic\\0.9 World Bosses.lua
-- #IMPORT: 01 - Dungeons Raids\\1 - Classic\\1.0 Molten Core.lua
-- #IMPORT: 01 - Dungeons Raids\\1 - Classic\\1.5 Onyxia's Lair.lua
-- #IMPORT: 01 - Dungeons Raids\\1 - Classic\\1.6 Blackwing Lair.lua
-- #IMPORT: 01 - Dungeons Raids\\1 - Classic\\1.7 Zul'Gurub.lua
-- #IMPORT: 01 - Dungeons Raids\\1 - Classic\\2.5 Ruins of Ahn'Qiraj.lua
-- #IMPORT: 01 - Dungeons Raids\\1 - Classic\\2.6 Temple of Ahn'Qiraj.lua
-- #IMPORT: 01 - Dungeons Raids\\1 - Classic\\3.0 Naxxramas.lua
-- #IMPORT: 01 - Dungeons Raids\\1 - Classic\\Blackfathom Deeps.lua
-- #IMPORT: 01 - Dungeons Raids\\1 - Classic\\Blackrock Depths.lua
-- #IMPORT: 01 - Dungeons Raids\\1 - Classic\\Lower Blackrock Spire.lua
-- #IMPORT: 01 - Dungeons Raids\\1 - Classic\\Deadmines.lua
-- #IMPORT: 01 - Dungeons Raids\\1 - Classic\\Dire Maul.lua
-- #IMPORT: 01 - Dungeons Raids\\1 - Classic\\Gnomeregan.lua
-- #IMPORT: 01 - Dungeons Raids\\1 - Classic\\Maraudon.lua
-- #IMPORT: 01 - Dungeons Raids\\1 - Classic\\Ragefire Chasm.lua
-- #IMPORT: 01 - Dungeons Raids\\1 - Classic\\Razorfen Downs.lua
-- #IMPORT: 01 - Dungeons Raids\\1 - Classic\\Razorfen Kraul.lua
-- #IMPORT: 01 - Dungeons Raids\\1 - Classic\\Scarlet Halls.lua
-- #IMPORT: 01 - Dungeons Raids\\1 - Classic\\Scarlet Monastery.lua
-- #IMPORT: 01 - Dungeons Raids\\1 - Classic\\Scholomance.lua
-- #IMPORT: 01 - Dungeons Raids\\1 - Classic\\Shadowfang Keep.lua
-- #IMPORT: 01 - Dungeons Raids\\1 - Classic\\Stratholme.lua
-- #IMPORT: 01 - Dungeons Raids\\1 - Classic\\The Stockade.lua
-- #IMPORT: 01 - Dungeons Raids\\1 - Classic\\The Temple of Atal'hakkar.lua
-- #IMPORT: 01 - Dungeons Raids\\1 - Classic\\Uldaman.lua
-- #IMPORT: 01 - Dungeons Raids\\1 - Classic\\Wailing Caverns.lua
-- #IMPORT: 01 - Dungeons Raids\\1 - Classic\\Zul'Farrak.lua

-- Burning Crusade
-- #IMPORT: 01 - Dungeons Raids\\2 - Burning Crusade\\0 - Metadata.lua
-- #IMPORT: 01 - Dungeons Raids\\2 - Burning Crusade\\0.1 World Bosses.lua
-- #IMPORT: 01 - Dungeons Raids\\2 - Burning Crusade\\1 Karazhan (Raid).lua
-- #IMPORT: 01 - Dungeons Raids\\2 - Burning Crusade\\2 Gruul's Lair.lua
-- #IMPORT: 01 - Dungeons Raids\\2 - Burning Crusade\\3 Magtheridon's Lair.lua
-- #IMPORT: 01 - Dungeons Raids\\2 - Burning Crusade\\4 Serpentshrine Cavern.lua
-- #IMPORT: 01 - Dungeons Raids\\2 - Burning Crusade\\5 The Eye.lua
-- #IMPORT: 01 - Dungeons Raids\\2 - Burning Crusade\\6 The Battle for Mount Hyjal.lua
-- #IMPORT: 01 - Dungeons Raids\\2 - Burning Crusade\\7 The Black Temple.lua
-- #IMPORT: 01 - Dungeons Raids\\2 - Burning Crusade\\7.5 Zul'Aman.lua
-- #IMPORT: 01 - Dungeons Raids\\2 - Burning Crusade\\8 Sunwell Plateau.lua
-- #IMPORT: 01 - Dungeons Raids\\2 - Burning Crusade\\Auchenai Crypts.lua
-- #IMPORT: 01 - Dungeons Raids\\2 - Burning Crusade\\Hellfire Ramparts.lua
-- #IMPORT: 01 - Dungeons Raids\\2 - Burning Crusade\\Magisters' Terrace.lua
-- #IMPORT: 01 - Dungeons Raids\\2 - Burning Crusade\\Mana Tombs.lua
-- #IMPORT: 01 - Dungeons Raids\\2 - Burning Crusade\\Old Hillsbrad Foothills.lua
-- #IMPORT: 01 - Dungeons Raids\\2 - Burning Crusade\\Sethekk Halls.lua
-- #IMPORT: 01 - Dungeons Raids\\2 - Burning Crusade\\Shadow Labyrinth.lua
-- #IMPORT: 01 - Dungeons Raids\\2 - Burning Crusade\\The Arcatraz.lua
-- #IMPORT: 01 - Dungeons Raids\\2 - Burning Crusade\\The Black Morass.lua
-- #IMPORT: 01 - Dungeons Raids\\2 - Burning Crusade\\The Blood Furnace.lua
-- #IMPORT: 01 - Dungeons Raids\\2 - Burning Crusade\\The Botanica.lua
-- #IMPORT: 01 - Dungeons Raids\\2 - Burning Crusade\\The Mechanar.lua
-- #IMPORT: 01 - Dungeons Raids\\2 - Burning Crusade\\The Shattered Halls.lua
-- #IMPORT: 01 - Dungeons Raids\\2 - Burning Crusade\\The Slave Pens.lua
-- #IMPORT: 01 - Dungeons Raids\\2 - Burning Crusade\\The Steamvault.lua
-- #IMPORT: 01 - Dungeons Raids\\2 - Burning Crusade\\The Underbog.lua

-- Wrath of the Lich King
-- #IMPORT: 01 - Dungeons Raids\\3 - Wrath of the Lich King\\0 - Metadata.lua
-- #IMPORT: 01 - Dungeons Raids\\3 - Wrath of the Lich King\\1 Vault of Archavon.lua
-- #IMPORT: 01 - Dungeons Raids\\3 - Wrath of the Lich King\\2 Naxxramas.lua
-- #IMPORT: 01 - Dungeons Raids\\3 - Wrath of the Lich King\\3 The Obsidian Sanctum.lua
-- #IMPORT: 01 - Dungeons Raids\\3 - Wrath of the Lich King\\4 The Eye of Eternity.lua
-- #IMPORT: 01 - Dungeons Raids\\3 - Wrath of the Lich King\\9 The Ruby Sanctum.lua

-- Outdoor Zones

-- Eastern Kingdoms
-- #IMPORT: 02 - Outdoor Zones\\02 Eastern Kingdoms\\0 - Metadata.lua
-- #IMPORT: 02 - Outdoor Zones\\02 Eastern Kingdoms\\1 - Silvermoon City.lua
-- #IMPORT: 02 - Outdoor Zones\\02 Eastern Kingdoms\\Deeprun Tram.lua
-- #IMPORT: 02 - Outdoor Zones\\02 Eastern Kingdoms\\Eversong Woods.lua
-- #IMPORT: 02 - Outdoor Zones\\02 Eastern Kingdoms\\Ghostlands.lua
-- #IMPORT: 02 - Outdoor Zones\\02 Eastern Kingdoms\\Isle of Quel'Danas.lua
root("Zones", m(EASTERN_KINGDOMS, {
	["OnUpdate"] = [[function(t) table.sort(t.g, function (a, b) return string.lower(a.isRaid and (" " .. a.text) or a.text) < string.lower(b.isRaid and (" " .. b.text) or b.text) end)  end]],
}));

-- Outland
-- #IMPORT: 02 - Outdoor Zones\\03 Outland\\0 - Metadata.lua
-- #IMPORT: 02 - Outdoor Zones\\03 Outland\\1 - Shattrath City.lua
-- #IMPORT: 02 - Outdoor Zones\\03 Outland\\Blade's Edge Mountains.lua
-- #IMPORT: 02 - Outdoor Zones\\03 Outland\\Hellfire Peninsula.lua
-- #IMPORT: 02 - Outdoor Zones\\03 Outland\\Nagrand.lua
-- #IMPORT: 02 - Outdoor Zones\\03 Outland\\Netherstorm.lua
-- #IMPORT: 02 - Outdoor Zones\\03 Outland\\Shadowmoon Valley.lua
-- #IMPORT: 02 - Outdoor Zones\\03 Outland\\Terokkar Forest.lua
-- #IMPORT: 02 - Outdoor Zones\\03 Outland\\Zangarmarsh.lua

-- Holidays
-- #IMPORT: 21 - Holidays\\07 - Brewfest\\Brewfest.lua
-- #IMPORT: 21 - Holidays\\04 - Children's Week\\Children's Week.lua
-- #IMPORT: 21 - Holidays\\10 - Day of the Dead\\Day of the Dead.lua
-- #IMPORT: 21 - Holidays\\12 - Feast of Winter Veil\\Feast of Winter Veil.lua
-- #IMPORT: 21 - Holidays\\09 - Hallow's End\\Hallow's End.lua
-- #IMPORT: 21 - Holidays\\08 - Harvest Festival\\Harvest Festival.lua
-- #IMPORT: 21 - Holidays\\02 - Love is in the Air\\Love is in the Air.lua
-- #IMPORT: 21 - Holidays\\01 - Lunar Festival\\Lunar Festival.lua
-- #IMPORT: 21 - Holidays\\05 - Midsummer Fire Festival\\Midsummer Fire Festival.lua
-- #IMPORT: 21 - Holidays\\03 - Noblegarden\\Noblegarden.lua
-- #IMPORT: 21 - Holidays\\11 - Pilgrim's Bounty\\Pilgrim's Bounty.lua
-- #IMPORT: 21 - Holidays\\06 Pirates' Day.lua
-- #IMPORT: 21 - Holidays\\00b - Stranglethorn Fishing Extravaganza\\Stranglethorn Fishing Extravaganza.lua

-- World Events
-- #IMPORT: 07 - Events\\The Ahn'Qiraj War Effort\\The Ahn'Qiraj War Effort.lua
-- #IMPORT: 07 - Events\\The Opening of the Dark Portal\\The Opening of the Dark Portal.lua
-- #IMPORT: 07 - Events\\The Scepter of the Shifting Sands\\The Scepter of the Shifting Sands.lua
-- #IMPORT: 07 - Events\\The Scourge Invasion\\The Scourge Invasion.lua
-- #IMPORT: 07 - Events\\The Silithyst Must Flow\\The Silithyst Must Flow.lua

-- Craftables
-- #IMPORT: 10 - Craftables\\01 - Classic.lua
-- #IMPORT: 10 - Craftables\\02 - Burning Crusade.lua

-- Professions
-- #IMPORT: 11 - Professions\\Beast Training\\Beast Training.lua
-- #IMPORT: 11 - Professions\\Cooking\\Cooking.lua
-- #IMPORT: 11 - Professions\\First Aid\\First Aid.lua
-- #IMPORT: 11 - Professions\\Fishing\\Fishing.lua
-- #IMPORT: 11 - Professions\\Herbalism\\Herbalism.lua
-- #IMPORT: 11 - Professions\\Jewelcrafting\\Jewelcrafting.lua
-- #IMPORT: 11 - Professions\\Mining\\Mining.lua
-- #IMPORT: 11 - Professions\\Poisons\\Poisons.lua
-- #IMPORT: 11 - Professions\\Runeforging\\Runeforging.lua
-- #IMPORT: 11 - Professions\\Skinning\\Skinning.lua

-- Promotions
-- #IMPORT: 12 - Promotions\\BlizzCon.lua
-- #IMPORT: 12 - Promotions\\Collector's Editions.lua
-- #IMPORT: 12 - Promotions\\Diablo 20th Anniversary.lua
-- #IMPORT: 12 - Promotions\\Hearthstone.lua
-- #IMPORT: 12 - Promotions\\Heroes of the Storm.lua
-- #IMPORT: 12 - Promotions\\iCoke.lua
-- #IMPORT: 12 - Promotions\\Miscellaneous.lua
-- #IMPORT: 12 - Promotions\\Recruit A Friend.lua
-- #IMPORT: 12 - Promotions\\Scroll of Resurrection.lua
-- #IMPORT: 12 - Promotions\\Spirit of Competition.lua
-- #IMPORT: 12 - Promotions\\Trading Card Game.lua
-- #IMPORT: 12 - Promotions\\Warcraft Movie.lua